config/routes.rb
Rails.application.routes.draw do
  resources :notes do
    resources :comments
  end
  devise_for :users
  root 'notes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :note
  belongs_to :user
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :notes
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_note, only: [:create, :show, :edit, :update, :destroy]

  def create

    @comment = @note.comments.build(comments_params)
    @comment.user = current_user
    @comment.save

    redirect_to notes_url
  end

  def edit
  end

  def show
  end

  def update

    respond_to do |format|
      if @comment.update(comments_params)
        format.html { redirect_to root_url, notice: 'Comment was successfully update.' }
      #format.jason { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.jason { render jason: @comment.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @note = Note.find(params[:note_id])
    @comment = @note.comments.find(params[:id]).destroy

    redirect_to notes_url
  end

  private

  def set_comment
    p "___________________________"
    p @comment
    @comment = Comment.find(params[:id])

  end
  def set_note
    @note = Note.find(params[:note_id])

  end

  def comments_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:index, :create]

  # GET /notes
  # GET /notes.json
  def index

    @notes = @user.notes.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
@user = current_user
    @note = Note.new(note_params)
    @note = @user.notes.build(note_params)


    #

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.


    def set_user
      @user = current_user

    end

    def set_note
      p "___________________________"
      p @note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.content %>
  <%= link_to "Delete", note_comment_path(comment.note, comment), method: :delete %>
  <%= link_to "Edit", edit_note_comment_path(comment.note, comment)%>

</p>

app/views/comments/_form.html.erb
<%= form_with(model: comment, url:[note, comment],  local: true) do |form| %>

<% if comment.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(comment.errors.count, "error") %> prohibited this note from being saved:</h2>

    <ul>
    <% comment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment , note: @note %>

<%= link_to 'Back', root_url %>

app/views/comments/index.html.erb
<h4> Comments </h4>

         <%= render note.comments %>

       <% end %>
<hr>
       <p> Add Your Points : As comments here -- </p>
       <%= form_for([note, note.comments.build]) do |f| %>
         <%= f.text_area :content %>
         <%= submit_tag "Add" %>
       <% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notesapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note, local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>Notes</h1>
<%= link_to 'New Notes', new_note_path %>
<%= link_to 'Logout', destroy_user_session_path, method: :delete %>
<br>
<br>

<% @notes.each do |note| %>
  <div style="border: 1px solid black; background-color: #add8e6; width: 400px">
    <h3><%= note.description %></h3>
    <%= time_ago_in_words(note.created_at) %> ago by <%= note.user.email %>
    <br>

    <%= link_to 'Edit', edit_note_path(note) %>

    <%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are You Sure?' } %>
    <% if note.comments.any?%>
    <h4>Comments</h4>

      <%= render note.comments %>
      <% end %>



        <hr>

    <p>Add Comments</p>

    <%= form_for([note, note.comments.build]) do |f| %>
      <%= f.text_area :content %>
      <%= submit_tag "Add" %>
      <% end %>

  </div>

  <br>
  <br>
<% end %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @note.description %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>